version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongo:/data/db

  scrapper:
    build: .
    user: 1000:1000
    restart: always
    depends_on:
      - mongo
    command: 'npm start'
    volumes:
      - ./logs:/usr/src/app/logs
